/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FoundRouteImport } from './routes/found'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LostRouteImport } from './routes/lost'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportFoundRouteImport } from './routes/report-found'
import { Route as ReportLostRouteImport } from './routes/report-lost'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFoundRoute = ReportFoundRouteImport.update({
  id: '/report-found',
  path: '/report-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLostRoute = ReportLostRouteImport.update({
  id: '/report-lost',
  path: '/report-lost',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/help': typeof HelpRoute
  '/lost': typeof LostRoute
  '/my-reports': typeof MyReportsRoute
  '/profile': typeof ProfileRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/staff': typeof StaffRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/help': typeof HelpRoute
  '/lost': typeof LostRoute
  '/my-reports': typeof MyReportsRoute
  '/profile': typeof ProfileRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/staff': typeof StaffRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/found': typeof FoundRoute
  '/help': typeof HelpRoute
  '/lost': typeof LostRoute
  '/my-reports': typeof MyReportsRoute
  '/profile': typeof ProfileRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/staff': typeof StaffRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/found'
    | '/help'
    | '/lost'
    | '/my-reports'
    | '/profile'
    | '/report-found'
    | '/report-lost'
    | '/staff'
    | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/found'
    | '/help'
    | '/lost'
    | '/my-reports'
    | '/profile'
    | '/report-found'
    | '/report-lost'
    | '/staff'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/found'
    | '/help'
    | '/lost'
    | '/my-reports'
    | '/profile'
    | '/report-found'
    | '/report-lost'
    | '/staff'
    | '/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FoundRoute: typeof FoundRoute
  HelpRoute: typeof HelpRoute
  LostRoute: typeof LostRoute
  MyReportsRoute: typeof MyReportsRoute
  ProfileRoute: typeof ProfileRoute
  ReportFoundRoute: typeof ReportFoundRoute
  ReportLostRoute: typeof ReportLostRoute
  StaffRoute: typeof StaffRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-found': {
      id: '/report-found'
      path: '/report-found'
      fullPath: '/report-found'
      preLoaderRoute: typeof ReportFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-lost': {
      id: '/report-lost'
      path: '/report-lost'
      fullPath: '/report-lost'
      preLoaderRoute: typeof ReportLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FoundRoute: FoundRoute,
  HelpRoute: HelpRoute,
  LostRoute: LostRoute,
  MyReportsRoute: MyReportsRoute,
  ProfileRoute: ProfileRoute,
  ReportFoundRoute: ReportFoundRoute,
  ReportLostRoute: ReportLostRoute,
  StaffRoute: StaffRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
